modLoader = "javafml"
loaderVersion = "[9,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "captcha"
version = "${version}"
displayName = "Simple Captcha"
authors = "tuples"
description = '''
Funny captcha prank for your friends
'''
#logoFile = ""

[[dependencies.captcha]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.captcha]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.captcha]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "captcha.mixins.json"
