name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: # allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mc_version: [1.21.1, 1.21.8]
        include:
          - mc_version: 1.21.1
            mc_version_suffix: 1.21
            yarn: 1.21.1+build.3
            loader_version: 0.17.2
            fabric_version: 0.116.6+1.21.1
          - mc_version: 1.21.8
            mc_version_suffix: 1.21.8
            yarn: 1.21.8+build.1
            loader_version: 0.17.2
            fabric_version: 0.116.6+1.21.1
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build for ${{ matrix.mc_version }}
        run: |
          ./gradlew clean build \
            -Pminecraft_version=${{ matrix.mc_version }} \
            -Pmc_version_suffix=${{ matrix.mc_version_suffix }} \
            -Pyarn_mappings=${{ matrix.yarn }} \
            -Ploader_version=${{ matrix.loader_version }} \
            -Pfabric_version=${{ matrix.fabric_version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: captcha-${{ matrix.mc_version }}
          path: build/libs/simple-captcha-*-${{ matrix.mc_version_suffix }}.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
